SELECT * FROM TM_PRODUCTO WHERE PROD_ID = 2;

SELECT * FROM TM_PRODUCTO WHERE CAT_ID = 3;

SELECT * FROM TM_PRODUCTO WHERE CAT_ID IN (1,3);

SELECT * FROM TM_PRODUCTO WHERE PROD_NOM LIKE '%MAB%';

SELECT * FROM TM_PRODUCTO WHERE PROD_NOM LIKE '%SAM%';
