USE BDTESTE

SELECT * FROM TM_CATEGORIA

INSERT INTO TM_CATEGORIA
(CAT_NOM,FECH_CREA,EST)
VALUES
('NOTBOOK',GETDATE(),1)

SELECT * FROM TM_PRODUCTOS 

INSERT INTO TM_PRODUCTOS
(CAT_ID,PROD_NOMB,FECH_CREA,EST)
VALUES
(3,'HP',GETDATE(),1)

UPDATE TM_PRODUCTOS
SET
	FECH_CREA=GETDATE()
WHERE
	FECH_CREA IS NULL


SELECT * FROM TM_PRODUCTOS  WHERE PROD_ID = 2

UPDATE TM_PRODUCTOS
SET
	EST = 0
WHERE
	PROD_ID = 6

SELECT * FROM TM_PRODUCTOS

WHERE 
	CAT_ID = 3

SELECT * FROM TM_PRODUCTOS

WHERE 
	CAT_ID IN (1,3)

SELECT * FROM TM_PRODUCTOS

WHERE 
	PROD_NOMB LIKE '%DAI%'

CREATE PROCEDURE SP_L_PRODUCTO_02
@PROD_ID INT
AS
BEGIN
	SELECT 
		TM_CATEGORIA.CAT_ID,
		TM_PRODUCTOS.PROD_ID,
		TM_PRODUCTOS.CAT_ID AS Expr1,
		TM_PRODUCTOS.PROD_NOMB
	FROM     TM_CATEGORIA INNER JOIN
						TM_PRODUCTOS ON TM_CATEGORIA.CAT_ID = TM_PRODUCTOS.CAT_ID
	WHERE
	TM_PRODUCTOS.PROD_ID = 1

END

EXEC SP_L_PRODUCTO_02 3

SP_HELPTEXT SP_L_PRODUCTO_01
