CREATE PROCEDURE SP_L_PRODUCTO_01
AS
BEGIN
    SELECT 
        C.CAT_NOM,
        P.PROD_NOM,
        P.PROD_ID,
        P.CAT_ID
    FROM TM_PRODUCTO P
    INNER JOIN TMCATEGORIA C 
        ON P.CAT_ID = C.CAT_ID;
END;
GO

EXEC SP_L_PRODUCTO_01;
